### PR TITLE
Compiler rewrite

### PR DESCRIPTION
**Pull request by Spanfile**
Oh boy. It's working. See issue #83. Right now it's in a "the first properly working" state, so it still has work to do. The compiler-rewrite branch is now fully using this new one, there's no trace of the old, horrible switch-clause.

I will keep on improving it, most likely refactoring some parselets (I'm looking at you, queries and functions).

Feel free to ask anything about it, I'll try my best to justify my weird decisions for things. Do tell me if I forgot to implement something.

There's a bunch of tests related to the compiler that fail, not too sure what to do with them. Make test follow the new compiler, make compiler follow the tests?

You can merge this PR if you so wish, I'll keep working on this branch or on a new branch (something like compiler-improvement).

(I set the milestone to Rant 3 as the original issue had it as well.)

### CODE REVIEW

**Comment by cpancake** [comment]
Do all the tests pass? I'm not at home right now so I can't check.

**Comment by cpancake** [comment]
Er, all the tests that pass on the old compiler, that is. A few of them didn't pass :v

**Comment by cpancake** [comment]
The compiler should follow the tests. There's a few tests that don't work on the old compiler, so make a note of those.

**Comment by Spanfile** [comment]
Yup, got a few tests that passed on the old compiler but not on the new one. Will take a look at those.

**Comment by TheBerkin** [comment]
There are at least 10 tests failing because of stringe parent mismatch errors in RASequence's base constructor. I would like these to be fixed before I merge this PR.

**Comment by TheBerkin** [comment]
Also, I'm gonna be honest: some of this code is disgusting. For example, the `Parselet` class. 
* Properties and fields are spread throughout the class between methods and constructors. PLEASE put them all at the top.
* Why are you using prefixes on static members?
* Some constant strings marked as interpolated.
* Private/protected/public methods should be sorted by visibility.
* **Please always** specify "private" on private members. Don't leave it out.

Also, why does running an empty string print "EOF"? You shouldn't be treating EOF tokens as text. There is a Text token type for a reason.

I will consider writing a style guide to make sure everyone writes consistently styled code.

**Comment by Spanfile** [comment]
I'll have a look at the parent mismatches, I'm sure I've misplaced a token somewhere.

Is the code disgusting style-wise or is what I'm doing disgusting? I know there's quite a lot of (slow) Reflection magic going on, but all that makes the compiler very easy to extend upon.

I would really appreciate a style guide.

**Comment by TheBerkin** [comment]
I'm talking mostly about the style. I haven't looked closely enough at your code to give an opinion. However, the functionality issues I pointed out are serious ones, and I can break your compiler simply by adding trailing whitespace to a pattern.

I probably won't have time this weekend, but I'll see about writing a style guide in the next couple weeks when I'm not so busy with school.

**Comment by Spanfile** [comment]
I pushed a few fixes (not too happy with them, refactoring needed) for the whitespace issues.

About the at least 10 tests that fail: what are they? Here's all tests that fail for me on the master branch:
master

And here's all the tests that fail for me on the compiler-rewrite branch:
compiler-rewrite

I've managed to fix InvalidCarrierComponent("<noun>") and UnterminatedQuery, so I'm guessing the rest of the failing tests have failed with the old compiler as well?

**Comment by Spanfile** [comment]
There's some things I don't like too much in my implementations of things (such as the large pile of mess in FunctionParselet or BlockParselet), but they work. I can refactor them now if you want, or I can refactor after the merge.

**Comment by TheBerkin** [comment]
The stringe mismatch errors seem to have been fixed.

**Comment by Spanfile** [comment]
Yup, I've been working on the refactoring for some time now, trying to figure out some stuff and things.

I haven't done any style changes yet but I'll do those too before merging.

**Comment by Spanfile** [comment]
I have some ideas for refactoring the parselets even more, but they're a bit hacky and maybe not too necessary. The changes would just make the code cleaner, less DRY and more consistent but they would be (technically) less efficient than the current ones and (technically) use more memory. The downsides are so small, they might as well be non-existent, but they're still there and may show with large and/or complex Rant patterns.

**Comment by Spanfile** [comment]
I thought about the ideas I had a bit more and came to the conclusion that while they may make the code "better", they'd just introduce possibilities for weird bugs and confusion.

I'm happy with the compiler as it is now, I haven't found any more bugs to fix and all the compiler-related tests pass. If anything comes up, do ask.

Feel free to merge, I'll give you the honour.

**Comment by TheBerkin** [comment]
The deed is done.

**Pull request merged**
